pdf-2-xls/config/routes.rb
require 'constants'
Trap::Application.routes.draw do
 
  match "/#{DEFAULT_URL}" => 'trap#index' ,via: [:get, :post]
  match "/#{DEFAULT_URL}/:id" => 'trap#show' ,via: [:get, :post]
  match "/#{DEFAULT_URL}/:id/requests/:request_id" => 'trap#show_request_details' ,via: [:get, :post]
  match "/#{DEFAULT_URL}/:id/requests" => 'trap#show_request' ,via: [:get, :post]
  get '/trap/welcome'
  root 'trap#welcome'

  get "pdf_to_xls/index"
  get "pdf_to_xls/show"
  get "pdf_to_xls/present"
  post "pdf_to_xls/index"
  post "pdf_to_xls/show"
  post "pdf_to_xls/present"
  post "pdf_to_xls/change_page"
  post "pdf_to_xls/show_selected"
  match "/error" =>"pdf_to_xls#error" , via: [:get, :post]

  

end

pdf-2-xls/app/models/requests.rb
class Requests < ActiveRecord::Base
end

pdf-2-xls/app/controllers/application_controller.rb
require 'constants'
#Created by : Ksolves 
#Created at : 27-Aug-2014

class ApplicationController < ActionController::Base
  	# "trap_request" Method will be triggered before any other method
  	before_filter :trap_request
  	# Prevent CSRF attacks by raising an exception.
  	# For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception

  	# Method to trap to request and save in database
  	def trap_request  	
	   
	    # This will check that either we have to trap this one or not
      	if METHOD_TO_TRAP.include?(params[:action].to_s)
      		res={trap_id:params[:id], request_date:Date.today ,remote_ip:request.remote_ip.to_s, request_method:request.method.to_s, scheme:request.method.to_s, query_string:request.query_string.to_s, query_params:request.params.inspect, cookies:request.cookies.inspect, headers:request.headers.inspect, original_fullpath:request.original_fullpath.to_s, request_method:request.request_method.to_s, referer:request.referer.to_s, fullpath:request.fullpath.to_s,}
      		r=Requests.create res
      	end
	   
 	end
end

pdf-2-xls/app/controllers/pdf_to_xls_controller.rb
require 'json'
class PdfToXlsController < ApplicationController
  	def index
  	end
  	def show_selected
  		@selected_data=params[:selected_data]
  		respond_to do |format|
		  	format.xls	
		end
  	end
  	def show
  		begin
	  		file = params[:source]
			read_pdf(file)
			respond_to do |format|
			  	format.html
			  	format.xls	
			end
		rescue Exception => e
			flash[:error]=e.message
  			redirect_to "/error"
  		end
  	end

	def present

		respond_to do |format|
		  	format.html
		  	format.xls	
		end
	end
	def error
		
	end
	def change_page
		file=params[:source]
		read_pdf(file)
		page_no=params[:page_number].to_i
		@res=@result[page_no]
		respond_to do |format|
		 	format.js
		end
	end
	def read_pdf(file)
		@reader = PDF::Reader.new(file)
			text=''
			count=0
			@response=[]
			@result=[]
			@reader.pages.each do |page|
				count=count+1	  
				@result[count]=[]
			 	text=page.text.split("\n")
			  	text.each do |tt|
			  		#puts "+++++++++ #{tt}"
			  		r=tt.split(" ")
			  		@result[count] << r
			  		@response << r
			 	end	
			  	
			end
	end
end

pdf-2-xls/app/controllers/trap_controller.rb
#Created by : Ksolves 
#Created at : 27-Aug-2014
class TrapController < ApplicationController
  def index
  end

  def show
  end
  #Method to show all requests
  def show_request
  	@requests=Requests.where("trap_id=?",params[:id])
  end
  #Method to show details of a selected request
  def show_request_details
  	 @request_d=Requests.find(params[:request_id])
  end
end

pdf-2-xls/app/helpers/application_helper.rb
module ApplicationHelper
end

pdf-2-xls/app/helpers/pdf_to_xls_helper.rb
module PdfToXlsHelper
end

pdf-2-xls/app/helpers/trap_helper.rb
module TrapHelper
end

pdf-2-xls/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Ksolves Apps</title>
    <%= stylesheet_link_tag   "sb-admin-2.css", "bootstrap.min.css","application", media: "all", "data-turbolinks-track" => true %>
    <link href="/assets/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">
    <link href="/assets/plugins/dataTables.bootstrap.css" rel="stylesheet">
    <link href="/assets/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <%= javascript_include_tag "application","jquery-1.7.1.min.js","jquery.selection.js","sb-admin-2.js","bootstrap.min.js", "data-turbolinks-track" => true %> 
  	
    <script src="/assets/plugins/metisMenu/metisMenu.min.js"></script>
	<script src="/assets/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="/assets/plugins/dataTables/dataTables.bootstrap.js"></script>
  	<%= csrf_meta_tags %>
</head>
<body>
	<div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
				<img class="img-responsive" src="/assets/logo.png" alt="">
            </div>
            
<%= yield %>

</body>
</html>

pdf-2-xls/app/views/pdf_to_xls/change_page.js.erb
var data='';
data+='<table>';
	<%@res.each do |res|%>
		data+='<tr>';
			<%res.each do |r| %>
				data+='<td>'+ "<%=r%>"+'</td>';
			<%end%>	
		data+='</tr>';
	<%end%>	
data+='</table>';
$("div#data_page").html(data);

pdf-2-xls/app/views/pdf_to_xls/error.html.erb
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse"></div>
    </div>
</nav>
<br/>

<div id="page-wrapper">
	<h1 class="page-header">ERROR</h1>
	<div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                Error
            </div>
            <div class="panel-body">
           		<div class="alert alert-danger">
                    <%=flash[:error]%>
                </div>
            </div>
        </div>
    </div>   
</div>

pdf-2-xls/app/views/pdf_to_xls/index.html.erb
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse"></div>
    </div>
</nav>
<br/>

<div id="page-wrapper">
	<h1 class="page-header">PDF To XLS</h1>
	<div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                Steps to be followed to convert PDF to XLS.
            </div>
            <div class="panel-body">
                <p class="lead"></p>
                <p> 1) Browse a PDF file (For testing purpose use KSolves.pdf). Click on the Scan PDF button to upload the PDF file.</p>
                <p> 2) The uploaded PDF file is displayed on the left side.</p>
                <p> 3) You can download the complete XLS of the PDF file by clicking on the "Download Complete XLS" button.</p>
                <p> 4) You can also select some data and imported that to XLS. For this please select a data first and then click on the "Select Data" button. The selected data is displayed on the right side. Then click on the "Import data to XLS" button to import the selected data in XLS format.</p>
                <p> 5) Click on the "Clear Data" button to reset the selected data.</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <h3 class="page-header"></h3>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Browse a PDF file, click on Scan PDF.
                </div>                                       
            </div>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
            	<center>
            		<table class="table table-striped table-bordered table-hover" id="dataTables-example" style="width: 40%;">
	                    <tbody>
	                    	<%=form_tag pdf_to_xls_show_path do %>
								<tr class="even gradeX">
	                        		<td><%= file_field_tag "source" ,:class=>"last1 pro1"%><td/> 
									<td><button class="btn btn-lg btn-warning" type="submit">Scan PDF</button></td> 
	                        	</tr>
	                       <%end%>
	               		</tbody>
                	</table>
            	</center>  
            </div>
        </div>
    </div>
</div>

pdf-2-xls/app/views/pdf_to_xls/present.html.erb
<h1>PdfToXls#present</h1>
<p>Find me in app/views/pdf_to_xls/present.html.erb</p>

pdf-2-xls/app/views/pdf_to_xls/show.html.erb
<%= javascript_tag "window._token = '#{form_authenticity_token}'" %>


<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse"></div>
    </div>
</nav>
<br/>
<h1 class="page-header">Scan PDF</h1>
<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            <p> * The uploaded PDF file is displayed on the left side.</p>
            <p> * You can download the complete XLS of the PDF file by clicking on the "Download Complete XLS" button.</p>
            <p> * You can also select some data and imported that to XLS. For this please select a data first and then click on the "Select Data" button. The selected data is displayed on the right side. Then click on the "Import data to XLS" button to import the selected data in XLS format.</p>
            <p> * Click on the "Clear Data" button to reset the selected data.</p>
        </div>                                       
    </div>
</div>
<div class="col-lg-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            Total no of pages : <%=@reader.pages.count%>
        </div>
        <div class="panel-body">
        	<%=form_tag pdf_to_xls_show_path(:format=>'xls') do %>
				<%= hidden_field_tag "source" ,params[:source] %> 
				<button class="btn btn-lg btn-warning" style="float:right;" type="submit">Download Complete XLS</button>
			<%end%>
       		Select page <%= select("page","no", (1..@reader.pages.count).step(1).collect {|p| [ "#{p}", p ] }) %>
       		<br/><br/>
       		Showing data for Page <%=@page_number.to_i%>
       		<br/><br/>
       		<button class="btn btn-lg btn-warning select" type="submit">Select Data</button>
       		<br/><br/>
       		<div class="scrollable" id="data_page">
				<table class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <tbody>
                    	<%@response.each do |res|%>
							<tr>
								<%res.each do |r| %>
									<td> <%=r%></td>
								<%end%>	
							</tr>
						<%end%>	
               		</tbody>
            	</table>
			</div>
				<div class="right scrollable">
					<button class="btn btn-lg btn-warning clear" type="submit">Clear Data</button>
					<br/><br/>
					<%=form_tag pdf_to_xls_show_selected_path(:format=>'xls') do %>
						<%= hidden_field_tag "selected_data"  %>
						<button class="btn btn-lg btn-warning generate" type="submit">Import data to xls</button>
				    <% end %>		
				    <br/><br/>
					<table class="table table-striped table-bordered table-hover" >
						<thead>
                            <tr>
                                <th>Sr. No</th>
                                <th>Name</th>
                                <th>Age</th>
                            </tr>
                        </thead>
	                    <tbody class="scrollable result">
	               		</tbody>
	            	</table>
				</div>	
	        </div>
	    </div>    
    </div>
</div>   

<script>



$('.select').click(function(){
	$('.result').append($.selection('html'));
	var d=$("#selected_data").val();
	d +=$.selection('html')
	$("#selected_data").val(d);

});

$('.clear').click(function(){
	$(".result").html('');
});
$("#page_no").change(function(){
	var no=$("#page_no").val();
	$.ajax({ type: 'post', url: "/pdf_to_xls/change_page",data: ({ 'page_number' :no,'authenticity_token' : window._token ,'source' :"<%=params[:source]%>"}),success: function(data){
    }});
});

$(".generate").click(function(){
	var no=$("#page_no").val();
	$.ajax({ type: 'post', url: "/pdf_to_xls/change_page",data: ({ 'page_number' :no,'authenticity_token' : window._token ,'source' :"<%=params[:source]%>"}),success: function(data){
    }});
});
</script>
<style>

.right{
	float: right;
	margin-top: -40%;
}
.scrollable{
	height: 450px;
    overflow: scroll;
    width: 45%;
}
</style>

pdf-2-xls/app/views/pdf_to_xls/show.xls.erb
<table>
<%@response.each do |res|%>
	<tr>
		<% if res.count > 0
			res.each do |r| %>
			<td> <%="#{r}     "%></td>
		<%end
		end%>	
	</tr>
<%end%>	

pdf-2-xls/app/views/pdf_to_xls/show_selected.xls.erb
<table>

	<%=raw @selected_data%>
</table>

pdf-2-xls/app/views/trap/index.html.erb
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse"></div>
    </div>
</nav>
<br/>

<div id="page-wrapper">
    <h1 class="page-header">Trap</h1>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                Steps to be followed to Trap a Request.
            </div>
            <div class="panel-body">
                <p class="lead"></p>
                <p>1) Click on any of the Secret URLs to trap a request.</p>
                <p>2) Clicking on any of the link, your request will be trapped.</p>
                <p>3) Click on the REQUESTS to see the requests made to this particular Trap ID.</p>
                <p>4) Clicking on any of the request, request details will be displayed.</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <h3 class="page-header">Secret URLs</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Select one of the following URLs, your request will be trapped .
                </div>                                       
            </div>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <center>
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example" style="width: 40%;">
                        <tbody>
                            <%for x in (0..20).step(5)%>
                                <tr class="even gradeX">
                                    <td> <a href="/<%=DEFAULT_URL%>/<%=x%>" >Click here to Trap the request (<%=x%> to <%=x+4%>)</a> </td> 
                                </tr>
                            <%end%>
                        </tbody>
                    </table>
                </center>
                
            </div>
        </div>
    </div>
</div>

pdf-2-xls/app/views/trap/show.html.erb
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse"></div>
    </div>
</nav>
<br/>

<div id="page-wrapper">
	<h1 class="page-header">Trap</h1>
	<div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                Ahh! Your request is trapped... Click on the REQUESTS to Track the requests.
            </div>
            <div class="panel-body">
                <p class="lead"></p>
                 <p class="lead">Track <a href="/<%=DEFAULT_URL%>/<%=params[:id]%>/requests">REQUESTS.</a></p>
            </div>
        </div>
    </div>
</div>    

pdf-2-xls/app/views/trap/show_request.html.erb
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse"></div>
    </div>
</nav>
<br/>

<div id="page-wrapper">
  <h1 class="page-header">Requests</h1>
    <div class="col-lg-4">
      <div class="panel panel-default">
          <div class="panel-heading">
              Click on one of the following requests and see the request details.
          </div>
          <div class="panel-body">
            <h4>Requests List</h4>
              <ol>
                <% @requests.each do |req|%>
                  <li><a href="/<%=DEFAULT_URL%>/<%=params[:id]%>/requests/<%=req.id%>"> Request Id:<%=req.id%></a>
                    &nbsp &nbsp &nbsp 
                   <span>Request Date:<%=req.request_date.strftime("%d %B %Y")%></span> 
                  </li>
                <%end %> 
              </ol>
          </div>
        </div>
    </div>
</div>

pdf-2-xls/app/views/trap/show_request_details.html.erb
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse"></div>
    </div>
</nav>
<br/>

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Request Details</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <p><a href="/<%=DEFAULT_URL%>/<%=params[:id]%>/requests"> Show Requests </a></p>
                </div>                       
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                                <tr>
                                    <th>Key</th>
                                    <th>Value</th>
                                </tr>
                            </thead>
                            <tbody>
                                <%keys=@request_d.attributes.keys%>
                                <%keys.each do |key|%>
                                    <tr class="even gradeC">
                                        <td><%=key%></td>
                                        <td><%=@request_d[key]%></td> 
                                    </tr>
                                <% end %>    
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
     
  

pdf-2-xls/app/views/trap/welcome.html.erb
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse"></div>
    </div>
</nav>

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">KSolves Ruby on Rails Apps</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Templates by KSolves
                </div>                       
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                                <tr>
                                    <th>Name of the App</th>
                                    <th>App Link</th>
                                    <th>GitHub Link</th>
                                    <th>Bit Bucket Link</th>
                                    <th>Description</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="odd gradeX">
                                    <td>Trap</td>
                                    <td><a target="_blank" href="/<%=DEFAULT_URL%>">Trap</a></td>
                                    <td><a target="_blank" href="https://github.com/kartiksolves/KSolve_RoR">Github Link for Trap</a></td>
                                    <td class="center"><a target="_blank" href="https://kartikksolves@bitbucket.org/kartikksolves/ksolves-ror.git">Bit Bucket link for Trap</a></td>
                                    <td>Trap is a tool to capture and display HTTP requests. This tool is useful during the development of apps that integrate with external services like webhooks etc. This Request Trap app provides these external services with an endpoint to which they can send requests and notifications. </td>
                                </tr>
                                <tr class="even gradeC">
                                    <td>PDF To XLS</td>
                                    <td><a target="_blank" href="/pdf_to_xls/index">PDF To XLS</a></td>
                                    <td><a target="_blank" href="https://github.com/kartiksolves/KSolve_RoR">Github Link for PDF To XLS</a></td>
                                    <td class="center"><a target="_blank" href="https://kartikksolves@bitbucket.org/kartikksolves/ksolves-ror.git">Bit Bucket link for PDF TO XLS</a></td>
                                    <td>PDF To XLS is a tool to convert a PDF file into XLS.This tool uses two gems "pdf-reader" and "to_xls" for the conversion process. This tool can also be helpful for the generation of XLS of the selected element of the uploaded PDF.</td>
                                </tr>
                                <tr class="odd gradeX">
                                    <td>KSolves Tweet</td>
                                    <td><a target="_blank" href="http://ksolves-tweet.herokuapp.com/" > KSolves Tweet </a></td>
                                    <td><a target="_blank" href="https://github.com/kartiksolves/KSolves-Tweet">Github Link for KSolves Tweet</a></td>
                                    <td class="center"><a target="_blank" href="https://kartikksolves@bitbucket.org/kartikksolves/ksolves-tweet.git">Bit Bucket link for KSolves Tweet</a></td>
                                    <td>Tweet is a tweet sharing ROR App. The input is a CSV file with list of cities. When it's 8am in any timezone, a random city is picked from that CSV file. A tweet string starting with "Good morning, CITYNAME" is created. Google map API is called so as to get the Google maps URL for that city. The URL is then passed through google URL shortener API. Google images API is used to get an image for that city with search query "City Country beautiful". Hence the final tweet string will be "Good morning, CITYNAME the Google Map URL and the PHOTO_URL"(where the photo is attached to the tweet as media). The tweet is shared, wait for the next timezone to hit 8am.
                                    </td>
                                </tr>
                                <tr class="even gradeX">
                                    <td>KSolves Stripe</td>
                                    <td><a target="_blank" href="http://stripe-ksolves.herokuapp.com/" > KSolves Stripe</a></td>
                                    <td><a target="_blank" href="https://github.com/kartiksolves/KSolves-Stripe.git">Github Link for KSolves Stripe</a></td>
                                    <td class="center"><a target="_blank" href="https://kartikksolves@bitbucket.org/kartikksolves/ksolves-stripe.git">Bit Bucket link for KSolves Stripe</a></td>
                                    <td>KSolves Stripe is an Online Payment Gateway demo app. The Payment is done through a secure payment gateway STRIPE.
                                        Once the user enters the LogIn Information, the app takes him to a form through which the user enters the credit card details. The test credit card details are displayed on the Demo App page itself. Once the information is submitted, the transaction information like date, amount, card-type, last four numbers of the credit card and transaction Id is displayed on the another page.
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
          
    <script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable();
    });
    </script>
